export const LOAD_CURRENT_USER = 'LOAD_CURRENT_USER'
export const UPDATE_USER       = 'UPDATE_USER'
export const LOAD_USERS        = 'LOAD_USERS'
export const LOAD_DISHES       = 'LOAD_DISHES'
export const SET_TITLE         = 'SET_TITLE'
export const SHOW_ALERT        = 'SHOW_ALERT'
export const ADD_TO_CART       = 'ADD_TO_CART'
