export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER'
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER'
export const UPDATE_USER          = 'UPDATE_USER'
export const LOAD_USERS           = 'LOAD_USERS'
export const REQUEST_DISHES       = 'REQUEST_DISHES'
export const RECEIVE_DISHES       = 'RECEIVE_DISHES'
export const SET_TITLE            = 'SET_TITLE'
export const SHOW_ALERT           = 'SHOW_ALERT'
export const ADD_TO_CART          = 'ADD_TO_CART'
export const INCR_CART_ITEM       = 'INCR_CART_ITEM'
export const DECR_CART_ITEM       = 'DECR_CART_ITEM'
export const CHECKOUT_REQUEST     = 'CHECKOUT_REQUEST'
export const RECEIVE_COMMENTS     = 'RECEIVE_COMMENTS'
// below refer: https://auth0.com/blog/secure-your-react-and-redux-app-with-jwt-authentication/
export const LOGIN_REQUEST        = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS        = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE        = 'LOGIN_FAILURE'
